[features]
seeds = true
skip-lint = false

[programs.localnet]
nft_lottery = "Lottery111111111111111111111111111111111111"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"

