[package]
name = "lottery"
version = "0.1.0"
description = "SVM token-only lottery skeleton"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "lottery"

[dependencies]
anchor-lang = { version = "0.30.1", features = ["init-if-needed"] }

